package model;

public final class CompoundInterestRecord {

    /**
     * The year number within the investment period that this record represents.
     * This value indicates the ordinal year of the investment, typically starting from 1
     * for the first year and incrementing sequentially for each subsequent year.
     */
    private final int year;
    /**
     * El capital inicial al comienzo del año para este registro de interés compuesto.
     *
     * Este valor representa el monto de capital disponible al inicio del período anual,
     * antes de que se calcule y agregue el interés del año. Para el primer año de inversión,
     * este valor coincide con el capital inicial de la inversión. Para años subsecuentes,
     * corresponde al capital de cierre del año anterior.
     */
    private final double openingCapital;
    /**
     * The amount of interest accumulated during this year of the investment period.
     * This value represents the difference between the closing capital and the opening capital,
     * calculated based on the investment's annual interest rate applied to the opening capital.
     */
    private final double interestEarned;
    /**
     * The capital amount at the end of the year after interest has been applied.
     * This value represents the sum of the opening capital and the interest earned during the year.
     * It becomes the opening capital for the subsequent year in compound interest calculations.
     */
    private final double closingCapital;

    /**
     * Constructs a new CompoundInterestRecord with the specified financial data for a given year.
     * Creates an immutable record representing the investment state including the year identifier,
     * the capital at the beginning of the year, the interest generated during the year,
     * and the resulting capital at year end.
     *
     * @param year the year for which this record applies
     * @param openingCapital the amount of capital at the beginning of the year
     * @param interestEarned the amount of interest generated during the year
     * @param closingCapital the total capital at the end of the year after adding interest
     */
    public CompoundInterestRecord(int year, double openingCapital,
                                  double interestEarned, double closingCapital) {
        this.year = year;
        this.openingCapital = openingCapital;
        this.interestEarned = interestEarned;
        this.closingCapital = closingCapital;
    }

    /**
     * Returns the year associated with this compound interest record.
     *
     * @return the year as an integer value
     */
    public int getYear() {
        return year;
    }

    /**
     * Returns the opening capital amount at the beginning of the year for this investment record.
     * The opening capital represents the total capital available at the start of the period,
     * before any interest is earned for this year. For the first year, this equals the initial
     * investment capital. For subsequent years, it equals the previous year's closing capital.
     *
     * @return the opening capital amount in monetary units
     */
    public double getOpeningCapital() {
        return openingCapital;
    }

    /**
     * Returns the interest earned for this investment record during the year.
     * This value represents the monetary gain generated by the investment
     * over the course of the year, calculated as the difference between
     * the closing capital and opening capital.
     *
     * @return the interest earned in monetary units
     */
    public double getInterestEarned() {
        return interestEarned;
    }

    /**
     * Returns the closing capital amount at the end of the year.
     * The closing capital represents the total value of the investment after applying
     * the interest earned to the opening capital for this period.
     *
     * @return the closing capital value in monetary units
     */
    public double getClosingCapital() {
        return closingCapital;
    }
}
